source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/CoderLawrence/WJSpecs.git'

use_frameworks!

target 'WJHomeModule_Example' do
  pod 'WJHomeModule', :path => '../'

  target 'WJHomeModule_Tests' do
    inherit! :search_paths

    
  end
end
